
# Generated by Django 5.2.1 on 2025-06-03 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Sarlavha')),
                ('desc', models.CharField(max_length=200, verbose_name='Izoh')),
                ('link', models.URLField(verbose_name='Havola')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Qo‘shilgan vaqti')),
            ],
        ),
        migrations.DeleteModel(
            name='cards',
        ),
    ]
