# Generated by Django 5.2.1 on 2025-07-03 07:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(error_messages={'unique': 'Bu username allaqachon ishlatilgan.'}, max_length=150, unique=True, validators=[django.core.validators.MinLengthValidator(5, message='Username kamida 5 ta belgidan iborat bo‘lishi kerak.')]),
        ),
    ]
