# Generated by Django 5.2.1 on 2025-06-05 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_category_kurs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kurs',
            name='description',
            field=models.TextField(max_length=200, verbose_name='Izoh'),
        ),
        migrations.AlterField(
            model_name='news',
            name='desc',
            field=models.TextField(max_length=200, verbose_name='Izoh'),
        ),
    ]
