# Generated by Django 5.2.1 on 2025-07-23 06:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_customuser_address_customuser_bio_customuser_gender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='owner_last_name',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='owner_name',
        ),
        migrations.AddField(
            model_name='projects',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
