# Generated by Django 5.2.1 on 2025-07-23 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_remove_projects_owner_last_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='owner',
        ),
        migrations.AddField(
            model_name='projects',
            name='owner_last_name',
            field=models.CharField(default=1, max_length=20, verbose_name='Familyangiz'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projects',
            name='owner_name',
            field=models.CharField(default=1, max_length=20, verbose_name='Ismingiz'),
            preserve_default=False,
        ),
    ]
