# Generated by Django 5.2.1 on 2025-06-05 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_alter_kurs_description_alter_news_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='Havola'),
        ),
    ]
