# Generated by Django 5.2.1 on 2025-07-25 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_remove_projects_owner_projects_owner_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='owner_username',
            field=models.CharField(db_index=True, default=1, max_length=150),
            preserve_default=False,
        ),
    ]
