# Generated by Django 5.2.1 on 2025-06-12 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_alter_news_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Sarlavha')),
                ('url', models.URLField(unique=True, verbose_name='Havola')),
                ('preview', models.ImageField(upload_to='images/', verbose_name='Eskiz')),
                ('description', models.TextField(max_length=200, verbose_name='Izoh')),
                ('source', models.CharField(max_length=30, verbose_name='Owner')),
            ],
        ),
    ]
