# Generated by Django 5.2.1 on 2025-06-13 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0006_dash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dash',
            name='title',
            field=models.CharField(max_length=70, verbose_name='Sarlavha'),
        ),
    ]
