# Generated by Django 5.2.1 on 2025-07-25 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0007_projects_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='owner_username',
        ),
    ]
