# Generated by Django 5.2.1 on 2025-06-14 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0007_alter_dash_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='kurs',
            name='owner_img',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Eskiz'),
        ),
    ]
