# Generated by Django 5.2.1 on 2025-06-15 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0008_kurs_owner_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=20, verbose_name='ismingiz')),
                ('owner_last_name', models.CharField(max_length=20, verbose_name='Familyangiz')),
                ('title', models.CharField(max_length=70, verbose_name='Sarlavha')),
                ('code', models.TextField(max_length=2000, verbose_name='kodingizni joylashtiring (max - 2000)')),
                ('url', models.URLField(blank=True, null=True, unique=True, verbose_name='Batafsil')),
                ('description', models.CharField(max_length=200, verbose_name='Izoh')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='Qo‘shilgan vaqti')),
            ],
        ),
        migrations.CreateModel(
            name='Category_pro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='my_app.category')),
            ],
        ),
    ]
