# Generated by Django 5.2.1 on 2025-06-16 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0009_projects_category_pro'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='code_files/'),
        ),
    ]
