# Generated by Django 5.2.1 on 2025-06-17 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0010_projects_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='code',
            field=models.TextField(blank=True, null=True, verbose_name='Kodingizni joylashtiring'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='owner_name',
            field=models.CharField(max_length=20, verbose_name='Ismingiz'),
        ),
    ]
