# Generated by Django 5.2.1 on 2025-06-19 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0011_alter_projects_code_alter_projects_owner_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='file',
            field=models.FileField(default=1, upload_to='code_files/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projects',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='Batafsil'),
        ),
    ]
