# Generated by Django 5.2.1 on 2025-06-19 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0012_alter_projects_file_alter_projects_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='my_app.category'),
        ),
        migrations.DeleteModel(
            name='Category_pro',
        ),
    ]
