# Generated by Django 5.2.1 on 2025-06-27 11:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0013_projects_category_delete_category_pro'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projects',
            options={'ordering': ('-publish',)},
        ),
        migrations.AddField(
            model_name='projects',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projects',
            name='publish',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='projects',
            name='slug',
            field=models.SlugField(default=1, max_length=255, unique_for_date='publish'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projects',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10),
        ),
        migrations.AddField(
            model_name='projects',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
