# Generated by Django 5.2.1 on 2025-06-28 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0014_alter_projects_options_projects_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='code_files/'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique_for_date='publish'),
        ),
    ]
